version: "3.8"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DOCKER_POSTGRES_DB}
      POSTGRES_USER: ${DOCKER_POSTGRES_USER}
      POSTGRES_PASSWORD: ${DOCKER_POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DOCKER_PORT}:${DOCKER_PORT}"

volumes:
  postgres_data:
